### ISSUE TITLE
take globs from .gitignore

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala-quickstart#13]
We should take the globs from .gitignore to ignore those files

**Comment by AbdealiJK** [comment]
Could you explain this issue a bit more ?
I have no idea what it's about

**Comment by sils1297** [comment]
The gitignore already contains globs to ignore e.g. generated files. We need to ignore e.g. for python projects the build directory in the coafile and the gitignore, this issue is about coala-quickstart using gitignore to generate the ignore setting for a coafile automatically.

**Comment by AbdealiJK** [comment]
Ahh, i see - so, it's auto filling the coafile ignore setting using
gitignore.

Just a note: hgignore has a similar syntax to gitignore - could do that too
?

Also, Our globs and gitignore globs are not similar.
For example, "build" in gitignore means **/build/** or similar in our
globs. But ".pyc" would be **/*.pyc. etc

**Comment by hypothesist** [comment]
@AbdealiJK I verified the following: (tracked - doesn't match, untracked - matches)

- with `.c`: `./file.c` is still tracked
- with `*.c`: `./file.c` is **untracked**
- with `*.c`: `./test1/file.c` is **untracked**
- with `.c`: `./test1/file.c` is obviously tracked
- with `**.c`: `./test1/file.c` and `./file.c` and are both **untracked**
- with `.c` and `*.c`: `./.c` is **untracked**
- with `file`: `./file` and `./test/file` are both **untracked**

Now consider only `./test/build/test2/file.c`.

- with `build` - **untracked**
- with `test` - tracked
- with `file` - tracked
- with `file.c` - **untracked**
- with `/build`, `/file.c` - tracked
- with `/test` - **untracked**
- with `test/`, `build/` - **untracked**

This is getting really weird and I'm super confused. However I found [this JavaScript library](https://github.com/EE/gitignore-to-glob) that converts from gitignore globs to some other glob format (however I'm unsure whether our glob is same as that).

**Comment by AbdealiJK** [comment]
Nearly All of those make sense to me, why are you confused? Have you read https://git-scm.com/docs/gitignore ?

The only case which doesn't make sense is
Pattern: 'test' tracking the file './test/build/test2/file.c'. Imo it shouldn't, can you recheck?

**Comment by hypothesist** [comment]
@AbdealiJK For instance `build` matches the file, which doesn't feel intutive to me (because it's not in the root directory). But that's probably because I'm thinking very verbose - I'd prefer for only `**/build/**` to match the file instead of `build`, but I totally understand `build` matching the file is simpler.

And you're right, `test` does make the file untracked. Sorry about that :sweat_smile:

**Comment by Makman2** [comment]
it's quite simple: every untracked file that matches a pattern in gitignore is ignored. If it's already tracked it isn't ignored. You can make it ignored again when you delete the file from the repository.

**Comment by hypothesist** [comment]
https://gist.github.com/hypothesist/d58073e5add2f1d5abc5e66183bddeb2

From Gitter:

@AbdealiJK [[ref]](https://gitter.im/coala-analyzer/coala?at=57544b5be8163f872c4e211a) -
- Not sure if \\ is also acceptable for windows (instead of the first /), so maybe test that out ?
- Your is_glob_exp checks for ( but what about ( in file names ? like the Windows pesky "Program files (x86)" ? Will it get confused by that ?
- You seem to be adding ** in the line 6,7 - what if it's not a directory ? like if I ignore /.coverage or /npm-log.txt or /Gemfile.lock
- `os.path.join(os.path.join(project_dir, "**"), line)` == `os.path.join(project_dir, "**", line)`
- What about a case like I do test.c in my gitignore and I happen to have a folder named test.c - will the contents of the folder be ignored by git ? (Your code does ignore the contents of the folder)

me [[ref]](https://gitter.im/coala-analyzer/coala?at=57583be4814a568071410f3e) -

- I just verified on Windows: /cov successfully ignores a file cov in the root directory.
- test (1|2) ignores a file called test (1|2) (literally). But test (1|2) never ignores a directory/file named test 1. Does git even support alternatives? Although test [12] ignores test 1. Anyway, a file called test [1] is not ignored when I add the same to .gitignore. However it is ignored when I escaped the [ and ]. So the fix is simple: before checking for *!?[] (not no parens, ?, |), remove all escaped characters?
- How about adding both ./cov and ./cov/** to the glob list? There can never exist a file and dir with the same name at the same place, so this should cover both and exactly the one that's there?
- git does ignore a directory called test.c when test.c is added to .gitignore
